dd  = {
        ('39', 'Amazon'): [{
                                "sn": 1,
                                "project_id": 39,
                                "status": "1",
                                "v": "14",
                                "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-17-597-billion",
                                "ptype": "Q1",
                                "year": "2019",
                                "fye": "12"
                            }, {
                                "sn": 2,
                                "project_id": 39,
                                "status": "1",
                                "v": "13",
                                "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-fourth-quarter-sales-20-724-billion",
                                "ptype": "Q4",
                                "year": "2018",
                                "fye": "12"
                            }, {
                                "sn": 3,
                                "project_id": 39,
                                "status": "1",
                                "v": "11",
                                "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-third-quarter-sales-29-566-billion",
                                "ptype": "Q3",
                                "year": "2018",
                                "fye": "12"
                            }, {
                                "sn": 4,
                                "project_id": 39,
                                "status": "1",
                                "v": "10",
                                "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-second-quarter-sales-39-529-billion",
                                "ptype": "Q2",
                                "year": "2018",
                                "fye": "12"
                            }, {
                                "sn": 5,
                                "project_id": 39,
                                "status": "1",
                                "v": "9",
                                "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-43-510-billion",
                                "ptype": "Q1",
                                "year": "2018",
                                "fye": "12"
                            }],
            ('39', 'JPMorgan') : [{
                                    "sn": 1,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "14",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-17-597-billion",
                                    "ptype": "Q1",
                                    "year": "2019",
                                    "fye": "12"
                                }, {
                                    "sn": 2,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "13",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-fourth-quarter-sales-20-724-billion",
                                    "ptype": "Q4",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 3,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "11",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-third-quarter-sales-29-566-billion",
                                    "ptype": "Q3",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 4,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "10",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-second-quarter-sales-39-529-billion",
                                    "ptype": "Q2",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 5,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "9",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-43-510-billion",
                                    "ptype": "Q1",
                                    "year": "2018",
                                    "fye": "12"
                                }],
        ('39', 'AmericanAirlines'): [{
                                    "sn": 1,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "14",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-17-597-billion",
                                    "ptype": "Q1",
                                    "year": "2019",
                                    "fye": "12"
                                }, {
                                    "sn": 2,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "13",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-fourth-quarter-sales-20-724-billion",
                                    "ptype": "Q4",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 3,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "11",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-third-quarter-sales-29-566-billion",
                                    "ptype": "Q3",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 4,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "10",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-second-quarter-sales-39-529-billion",
                                    "ptype": "Q2",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 5,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "9",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-43-510-billion",
                                    "ptype": "Q1",
                                    "year": "2018",
                                    "fye": "12"
                                }],
        ('39', 'GAPInc'): [{
                                    "sn": 1,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "14",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-17-597-billion",
                                    "ptype": "Q1",
                                    "year": "2019",
                                    "fye": "12"
                                }, {
                                    "sn": 2,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "13",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-fourth-quarter-sales-20-724-billion",
                                    "ptype": "Q4",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 3,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "11",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-third-quarter-sales-29-566-billion",
                                    "ptype": "Q3",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 4,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "10",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-second-quarter-sales-39-529-billion",
                                    "ptype": "Q2",
                                    "year": "2018",
                                    "fye": "12"
                                }, {
                                    "sn": 5,
                                    "project_id": 39,
                                    "status": "1",
                                    "v": "9",
                                    "doc_name": "https://ir.aboutamazon.com/news-releases/news-release-details/amazoncom-announces-first-quarter-sales-43-510-billion",
                                    "ptype": "Q1",
                                    "year": "2018",
                                    "fye": "12"
                                }],
}
